#define IDENTIFICADOR       0
#define ENTERO              1  
#define REAL                2  
#define CADENA              3  
#define TIPO                4  
#define OPSUMA              5  
#define OPMUL               6  
#define OPRELAC             7  
#define OPOR                8  
#define OPAND               9  
#define OPNOT               10  
#define OPIGUALDAD          11  
#define PUNTOCOMA           12  
#define COMA                13  
#define PARENTESISABRIR     14  
#define PARENTESISCERRAR    15  
#define CORCHETESABRIR      16  
#define CORCHETESCERRAR     17  
#define IGUAL               18  
#define IF                  19  
#define WHILE               20  
#define RETURN              21  
#define ELSE                22  
#define DOLLARSIGN          23  
#define ESPACIO             24 

//Tokens reglas
#define ERROR               -1 
#define PROGRAMA            24
#define DEFINICIONES        25
#define DEFINICION          26
#define DEFVAR              27
#define LISTAVAR            28
#define DEFFUNC             29
#define PARAMETROS          30
#define LISTAPARAM          31
#define BLOQFUNC            32
#define DEFLOCALES          33
#define DEFLOCAL            34
#define SENTENCIAS          35
#define SENTENCIA           36
#define OTRO                37
#define BLOQUE              38
#define VALORREGRESA        39
#define ARGUMENTOS          40
#define LISTAARGUMENTOS     41
#define TERMINO             42
#define LLAMADAFUNC         43
#define SENTENCIABLOQUE     44
#define EXPRESION           45